/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package serializers.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Things implements org.apache.thrift.TBase<Things, Things._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Things");

  private static final org.apache.thrift.protocol.TField THINGS_FIELD_DESC = new org.apache.thrift.protocol.TField("things", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThingsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThingsTupleSchemeFactory());
  }

  public List<Thing> things; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    THINGS((short)1, "things");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // THINGS
          return THINGS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.THINGS, new org.apache.thrift.meta_data.FieldMetaData("things", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Thing.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Things.class, metaDataMap);
  }

  public Things() {
  }

  public Things(
    List<Thing> things)
  {
    this();
    this.things = things;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Things(Things other) {
    if (other.isSetThings()) {
      List<Thing> __this__things = new ArrayList<Thing>();
      for (Thing other_element : other.things) {
        __this__things.add(new Thing(other_element));
      }
      this.things = __this__things;
    }
  }

  public Things deepCopy() {
    return new Things(this);
  }

  @Override
  public void clear() {
    this.things = null;
  }

  public int getThingsSize() {
    return (this.things == null) ? 0 : this.things.size();
  }

  public java.util.Iterator<Thing> getThingsIterator() {
    return (this.things == null) ? null : this.things.iterator();
  }

  public void addToThings(Thing elem) {
    if (this.things == null) {
      this.things = new ArrayList<Thing>();
    }
    this.things.add(elem);
  }

  public List<Thing> getThings() {
    return this.things;
  }

  public Things setThings(List<Thing> things) {
    this.things = things;
    return this;
  }

  public void unsetThings() {
    this.things = null;
  }

  /** Returns true if field things is set (has been assigned a value) and false otherwise */
  public boolean isSetThings() {
    return this.things != null;
  }

  public void setThingsIsSet(boolean value) {
    if (!value) {
      this.things = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case THINGS:
      if (value == null) {
        unsetThings();
      } else {
        setThings((List<Thing>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case THINGS:
      return getThings();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case THINGS:
      return isSetThings();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Things)
      return this.equals((Things)that);
    return false;
  }

  public boolean equals(Things that) {
    if (that == null)
      return false;

    boolean this_present_things = true && this.isSetThings();
    boolean that_present_things = true && that.isSetThings();
    if (this_present_things || that_present_things) {
      if (!(this_present_things && that_present_things))
        return false;
      if (!this.things.equals(that.things))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Things other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Things typedOther = (Things)other;

    lastComparison = Boolean.valueOf(isSetThings()).compareTo(typedOther.isSetThings());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetThings()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.things, typedOther.things);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Things(");
    boolean first = true;

    sb.append("things:");
    if (this.things == null) {
      sb.append("null");
    } else {
      sb.append(this.things);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThingsStandardSchemeFactory implements SchemeFactory {
    public ThingsStandardScheme getScheme() {
      return new ThingsStandardScheme();
    }
  }

  private static class ThingsStandardScheme extends StandardScheme<Things> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Things struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // THINGS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.things = new ArrayList<Thing>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  Thing _elem2; // required
                  _elem2 = new Thing();
                  _elem2.read(iprot);
                  struct.things.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setThingsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Things struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.things != null) {
        oprot.writeFieldBegin(THINGS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.things.size()));
          for (Thing _iter3 : struct.things)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThingsTupleSchemeFactory implements SchemeFactory {
    public ThingsTupleScheme getScheme() {
      return new ThingsTupleScheme();
    }
  }

  private static class ThingsTupleScheme extends TupleScheme<Things> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Things struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetThings()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetThings()) {
        {
          oprot.writeI32(struct.things.size());
          for (Thing _iter4 : struct.things)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Things struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.things = new ArrayList<Thing>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            Thing _elem7; // required
            _elem7 = new Thing();
            _elem7.read(iprot);
            struct.things.add(_elem7);
          }
        }
        struct.setThingsIsSet(true);
      }
    }
  }

}

